# Generated by Django 2.2.4 on 2019-09-08 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 9, 8, 11, 59, 17, 70631))),
            ],
        ),
    ]
